version: "3"

services:
    asiayo-pre-test:
        build:
          context: ./
          dockerfile: ./docker/Dockerfile
        restart: always
        container_name: asiayo-pre-test-chester-yang
        ports:
            - "8000:8000" # 以便 artisan serve 測試